import time

print("Hey! This is a remake of the `smol` deleted game Untitled_GaMe by NTBeta. If you're reading this, uh you're probably a friend of mine.")
print("Anyways, enjoy the game.")
time.sleep(3.0)
print("Welcome to the world of Untitled_GaMe, first I need to know your name.")
time.sleep(3.0)
print("What is it?")
time.sleep(3.0)
print("Your name is:")
name = input()
time.sleep(3.0)
print("So your name is " + name + "? Cool.")
time.sleep(3.0)
h = input()
